[2022-06-22 00:25:38,645: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 15:59:01,848: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 15:59:01,848: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 15:59:01,849: ERROR: stage_01_prepare_data]: while scanning a simple key
  in "configs/config.yaml", line 5, column 3
could not find expected ':'
  in "configs/config.yaml", line 6, column 3
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 25, in main
    config = read_yaml(config_path)
  File "c:\users\lmohan2\dvc-project-docs-template\lm_dvc_nlp_project-with-docs\src\utils\common.py", line 10, in read_yaml
    content = yaml.safe_load(yaml_file)
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\lmohan2\Anaconda3\envs\env\lib\site-packages\yaml\scanner.py", line 292, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "configs/config.yaml", line 5, column 3
could not find expected ':'
  in "configs/config.yaml", line 6, column 3
[2022-06-22 17:44:12,990: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 17:44:12,991: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 17:44:12,992: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-06-22 17:44:12,994: INFO: common]: yaml file: params.yaml loaded successfully
[2022-06-22 17:44:12,994: ERROR: stage_01_prepare_data]: string indices must be integers
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 28, in main
    source_data_dir= config['source_data']['data_dir']
TypeError: string indices must be integers
[2022-06-22 18:06:36,977: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 18:06:36,977: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 18:06:36,979: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-06-22 18:06:36,980: INFO: common]: yaml file: params.yaml loaded successfully
[2022-06-22 18:06:36,980: ERROR: stage_01_prepare_data]: string indices must be integers
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 28, in main
    source_data_dir= config['source_data']['data_dir']
TypeError: string indices must be integers
[2022-06-22 18:09:54,444: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 18:09:54,444: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 18:09:54,446: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-06-22 18:09:54,447: INFO: common]: yaml file: params.yaml loaded successfully
[2022-06-22 18:09:54,447: ERROR: stage_01_prepare_data]: name 'source_data' is not defined
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 28, in main
    source_data_dir= config[source_data][data_dir]
NameError: name 'source_data' is not defined
[2022-06-22 18:10:53,096: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 18:10:53,096: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 18:10:53,098: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-06-22 18:10:53,099: INFO: common]: yaml file: params.yaml loaded successfully
[2022-06-22 18:10:53,099: ERROR: stage_01_prepare_data]: string indices must be integers
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 28, in main
    source_data_dir= config['source_data']['data_dir']
TypeError: string indices must be integers
[2022-06-22 18:18:12,808: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 18:18:12,808: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 18:18:12,810: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-06-22 18:18:12,811: INFO: common]: yaml file: params.yaml loaded successfully
[2022-06-22 18:18:12,811: ERROR: stage_01_prepare_data]: string indices must be integers
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 28, in main
    source_data_dir= config["source_data"] ["data_dir"]
TypeError: string indices must be integers
[2022-06-22 18:24:38,043: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 18:24:38,044: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 18:24:38,045: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-06-22 18:24:38,046: INFO: common]: yaml file: params.yaml loaded successfully
[2022-06-22 18:24:38,046: ERROR: stage_01_prepare_data]: 'sourct_data'
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 29, in main
    source_data_file=config['sourct_data']['data_file']
KeyError: 'sourct_data'
[2022-06-22 18:26:02,986: INFO: stage_01_prepare_data]: 
********************
[2022-06-22 18:26:02,987: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2022-06-22 18:26:02,989: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-06-22 18:26:02,990: INFO: common]: yaml file: params.yaml loaded successfully
[2022-06-22 18:26:02,990: ERROR: stage_01_prepare_data]: string indices must be integers
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 63, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 32, in main
    split=params['prepare']['split']#split ratio
TypeError: string indices must be integers
